name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-22"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjYzMGRjMmUtMWZlZi00ZTJmLWI1ODktZjVkOTIyODQwNDJhIiwidGVuYW50X2lkIjoiOGNkZjM0MmI2ZGRjNTI3OTZhNjExNTZjN2FmYjM3MGUzMTA3ZTg3M2I3YjQxOTlhOGJhNTNlZWJkZWU1NzdmYiIsImludGVybmFsX3NlY3JldCI6ImFkNmIxYmVmLTIzZjYtNGRiZC1hZmJlLTM2Yzk1Zjk1YmJmMSJ9.VD_qKO9JZibcgAhdopa8I4zr4q6zi4HHj3gdltWxe9Q"
PULSE_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjYzMGRjMmUtMWZlZi00ZTJmLWI1ODktZjVkOTIyODQwNDJhIiwidGVuYW50X2lkIjoiOGNkZjM0MmI2ZGRjNTI3OTZhNjExNTZjN2FmYjM3MGUzMTA3ZTg3M2I3YjQxOTlhOGJhNTNlZWJkZWU1NzdmYiIsImludGVybmFsX3NlY3JldCI6ImFkNmIxYmVmLTIzZjYtNGRiZC1hZmJlLTM2Yzk1Zjk1YmJmMSJ9.VD_qKO9JZibcgAhdopa8I4zr4q6zi4HHj3gdltWxe9Q"
JWT_SECRET="mynameisdev"
