// Imports
const express = require("express");
const app = express();
const todoFile = require(`${__dirname}/file/todo.json`);
const fs = require("fs");
const { join } = require("path");

// Middlewares
app.use(express.json());
// console.log(todoFile);

// You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
//   - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
//   - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

//   Each todo has a title and a description. The title is a string and the description is a string.
//   Each todo should also get an unique autogenerated id every time it is created
//   The expected API endpoints are defined below,

// Route handlers

// 1.GET /todos - Retrieve all todo items
// Description: Returns a list of all todo items.
// Response: 200 OK with an array of todo items in JSON format.
// Example: GET http://localhost:3000/todos
app.get("/todos", (req, res) => {
  console.log(todoFile);
  return res.status(200).json(todoFile);
});
// 2.GET /todos/:id - Retrieve a specific todo item by ID
// Description: Returns a specific todo item identified by its ID.
// Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
// Example: GET http://localhost:3000/todos/123

app.get("/todos/:id", (req, res) => {
  const params = req.params.id;
  let todoItem;
  todoFile.map((todo) => {
    if (Number(todo?.id) === Number(params)) {
      // console.log(todo)
      todoItem = todo;
    }
  });
  if (todoItem) {
    return res.status(200).json(todoItem);
  } else {
    return res.status(404).json({
      message:
        "No data related to your request found!!! Please try with different id",
    });
  }
});
// 3. POST /todos - Create a new todo item
// Description: Creates a new todo item.
// Request Body: JSON object representing the todo item.
// Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
// Example: POST http://localhost:3000/todos
// Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
app.post("/todos", (req, res) => {
  const data = req.body;

  const id = todoFile.length + 1;
  const newTodo = { id, ...data };
  const allTodo = [...todoFile, newTodo];
  fs.writeFile(
    `${__dirname}/file/todo.json`,
    JSON.stringify(allTodo),
    function (err) {
      if (err) throw err;
      res.send("updated!!");
    }
  );
  // return res.json(data)
});

// 4. PUT /todos/:id - Update an existing todo item by ID
// Description: Updates an existing todo item identified by its ID.
// Request Body: JSON object representing the updated todo item.
// Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
// Example: PUT http://localhost:3000/todos/123
// Request Body: { "title": "Buy groceries", "completed": true }

app.put("/todos/:id", async (req, res) => {
  const { title, completed } = await req.body;
  const params = req.params.id;

  const updateTodo = todoFile.find((todo) => todo?.id === Number(params));
  updateTodo.title = title;
  updateTodo.completed = completed;

  const allTodo = todoFile.map((todo) =>
    todo.id === updateTodo.id ? updateTodo : todo
  );

  fs.writeFile(
    `${__dirname}/file/todo.json`,
    JSON.stringify(allTodo),
    function (error) {
      if (error) throw errow;
      return res.status(200).json({ message: "Todo Updated!!" });
    }
  );
});

// 5. DELETE /todos/:id - Delete a todo item by ID
// Description: Deletes a todo item identified by its ID.
// Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
// Example: DELETE http://localhost:3000/todos/123
app.delete("/todos/:id", (req, res) => {
  const paramsId = req.params.id;
  const newTodo = todoFile.filter((todo) => todo.id !== Number(paramsId));
  if (newTodo.length === todoFile.length) {
    return res.status(404).json({ message: "No Todo found!!" });
  }
  console.log(newTodo);
  fs.writeFile(`${__dirname}/file/todo.json`, JSON.stringify(newTodo), function (error) {
    if (error)
      return res.status(400).json({ message: "something went wrong!" });
    return res.status(200).json({ message: "Todo Deleled Successfully!!" });
  });
});
// - For any other route not defined in the server return 404

// http server port listen
app.listen(3000);
